--Do not edit this file unless you want to move your logging file or your script directory
rootpath = "sdmc:/script/"

logpath = rootpath .. "tas-script.log"

package.path = rootpath .. "?.lua;" .. package.path

SetupLog(logpath)

dofile(rootpath .. "main.lua")